#
# This workflow will install Python dependencies and run tests with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Unit tests with pytest

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build_and_test:

    runs-on: ubuntu-latest
#    defaults:
#      run:
#        working-directory: ./backend

    steps:
    - name: Checkout
      uses: actions/checkout@v4
#      with:
#        ref: branch

    - name: Set up Python 3.10
      uses: actions/setup-python@v5
      with:
        python-version: "3.10"
        cache: "pip"
        cache-dependency-path: |
          ./backend/requirements-ci.txt

    - name: Install dependencies
#      working-directory: ./backend
      run: |
        python -m pip install --upgrade pip
        pip install -r ./backend/requirements-ci.txt

    - name: Test with pytest
      working-directory: ./backend
      run: |
        pytest --tb=line -m unit

